### ISSUE TITLE
NV values in VLCB_4in4out start at 1

### ISSUE THREAD

**Issue by johnmholmes** [SvenRosvall/VLCB-Arduino#118]
Hi I notice that in the example the NV value starts at 1 should this be 0 I noticed this had been changed in Martin's original version, This would make the inputs work without having to change the value in the FCU as I found originally when testing that software.

**Comment by SvenRosvall** [comment]
John, not sure what you are asking for here. NV values describe how switches behave. See https://github.com/SvenRosvall/VLCB-Arduino/blob/main/docs/VLCB4in4out_README.md#node-variables

**Comment by johnmholmes** [comment]
Why would you want an input that does nothing?

**Comment by SvenRosvall** [comment]
You always want the option to disable things. Eventhough this is an Arduino sketch were you can take out unused switches, you may want to disable actions from some switches when the module is installed.
Anyways, the number associated with each switch behaviour is arbitrary. We could have used the numbers 17, 42, 123, 89 instead. Just feels more convenient to start from 1 and use 0 as a no-action.

**Comment by johnmholmes** [comment]
That is a fair point.

**Comment by johnmholmes** [comment]
Sven,
 
I am watching the progress of VLCB as I will be adopting a second bus on my layout over the next few months. CBUS is a good fit for my layout with the Arduino Nano being my hardware of choice. 
 
I do notice that the use of CBUS LEDS and button is the only way to introduce the module in the example sketch, compared to the version I have been working with of Martins. using the Arduino IDE.  I take it that this to keep within the MERG kit way of doing things. This approach seems to be a waste of available pins as we tend to avoid pins 0 and 1 as well IMO.
 
Is there a way of erasing the EEPROM or have these been added to one of the other libraries?
 
Best Regards
 
John
